version: "3.1"

services:
    mysql:
        image: mysql:5.7.29
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        ports:
            - "3306:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-proot"]
            timeout: 1s
            retries: 60
        volumes:
            - ./data/db:/var/lib/mysql
            - ./data/dump:/docker-entrypoint-initdb.d/
    mysql-test:
        image: mysql:5.7.29
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test-db
            MYSQL_USER: tester
            MYSQL_PASSWORD: tester
        ports:
            - "9306:3306"
